### ISSUE TITLE
Why not Button elements?

### ISSUE THREAD

**Issue by marcysutton** [iRaul/pushy-buttons#1]
I saw the README promotes using `<a class="btn btn--lg btn--blue" href="#">Button</a>`. Any reason why you're using links without hrefs when the whole concept is about buttons? 

I would recommend promoting the `<button>` element with classes since the push-button design will lead users to expect them to be buttons, which are triggered with the space bar as opposed to the enter key.

**Comment by iRaul** [comment]
I forgot to add it, sorry 😃 But it's obvious that an `<a>` need `href="#"` attribute.

Thanks for suggestion. You can contribute with this change if you want 😉

**Comment by iRaul** [comment]
Changed to `<button>` element.
